___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [60]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [74]:
print(np.__version__) 
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/nastia/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/nastia/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/nastia/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/nastia/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/nastia/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/nastia/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/nastia/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/nastia/anaconda3/include']


Створити вектор з 10 елементів, заповнений одиницями:

In [62]:
Z = np.ones(10)
Z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [63]:
Z = np.arange(0, 10, 1)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Створити матрицю 5 на 5, заповнену нулями:

In [64]:
Z = np.zeros((5,5))
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [71]:
Z = np.random.randint(0, 4, 20)
Z_nonzero = np.nonzero(Z)

print(f'Вектор: {Z}')
print(f'Індекси ненульових елементів: {Z1}')

Вектор: [3 0 0 1 1 1 1 1 2 3 3 2 1 1 3 3 0 1 3 2]
Індекси ненульових елементів: (array([ 1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 13, 14, 16, 17, 18, 19]),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [73]:
Z_mean = np.mean(Z)
Z_median = np.median(Z)
Z_std = np.std(Z)

print(f'Cереднє значення: {Z_mean}')
print(f'Медіана: {Z_median}')
print(f'Стандартне відхилення: {Z_std}')

Cереднє значення: 1.6
Медіана: 1.0
Стандартне відхилення: 1.0677078252031311


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [80]:
A = np.random.random((4, 2))
B = np.random.random((2, 2))
matrix_mult = np.dot(A, B)
matrix_mult

array([[0.23568964, 1.21858984],
       [0.12891286, 0.6606994 ],
       [0.06760645, 0.39465315],
       [0.09135348, 0.50395201]])

Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [84]:
C = matrix_mult.flatten('C')
C

array([0.23568964, 1.21858984, 0.12891286, 0.6606994 , 0.06760645,
       0.39465315, 0.09135348, 0.50395201])

In [85]:
C_min = np.min(C)
C_max = np.max(C)

print(f'Мінімальне значення вектора С: {C_min}')
print(f'Мінімальне значення вектора С: {C_max}')

Мінімальне значення вектора С: 0.06760644607955821
Мінімальне значення вектора С: 1.2185898414450995


In [151]:
C = np.where(C == C_max, 0, C)
C

array([0.23568964, 0.        , 0.12891286, 0.6606994 , 0.06760645,
       0.39465315, 0.09135348, 0.50395201])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [172]:
np.corrcoef(matrix_mult[:1], matrix_mult[1:])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [173]:
# ??????????????
corr = np.corrcoef(matrix_mult)
corr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [164]:
# ??????????????
corr1 = np.corrcoef(np.random.random((3, 3)))
corr1

array([[1.        , 0.57135749, 0.03909756],
       [0.57135749, 1.        , 0.84241247],
       [0.03909756, 0.84241247, 1.        ]])

Дано матрицю. Знайти ранг матриці:

In [95]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

In [96]:
rank_a = np.linalg.matrix_rank(a)
rank_a

3

Знайти визначник матриці:

In [98]:
determinant = np.linalg.det(a)
determinant

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [101]:
w, v = np.linalg.eig(a)
print(f'Власні числа матриці: {w}')
print(f'Власні вектори матриці: {v}')

Власні числа матриці: [14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]
Власні вектори матриці: [[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [112]:
a = np.random.randint(0,10,50)
a

array([2, 8, 1, 3, 6, 1, 8, 3, 0, 0, 7, 8, 5, 6, 0, 6, 8, 6, 4, 5, 3, 3,
       3, 2, 1, 2, 0, 5, 4, 1, 1, 1, 9, 5, 2, 2, 8, 9, 9, 9, 9, 1, 4, 7,
       0, 3, 4, 9, 5, 8])

In [113]:
most_freq = np.argmax(np.bincount(a))
most_freq

1

Виведіть лише парні числа, що діляться на 5:

In [178]:
a = np.random.randint(0,10,50)

In [179]:
answer = a[(a % 2 == 0) & (a % 5 == 0)]
answer = np.unique(answer)
answer

array([0])

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [144]:
A = np.array([[2, 5], [1, -10]])
B = np.array([1, 3])

res = np.linalg.solve(A, B)
res

array([ 1. , -0.2])